<?php

/**
 * @file
 * Implementation of photos_access.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CssCommand;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StreamWrapper\PrivateStream;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\node\NodeInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for form_node.
 */
function photos_access_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Get form node.
  $node = $form_state->getFormObject()->getEntity();
  if ($node && $node_type = $node->getType()) {
    if (\Drupal::config('photos.settings')->get('photos_access_' . $node_type)) {
      $nid = $node->id();
      $form['privacy'] = array(
        '#type' => 'details',
        '#title' => t('Privacy'),
        '#open' => TRUE,
        '#weight' => 1,
        '#tree' => TRUE,
      );
      $form['privacy']['vid'] = array('#type' => 'value', '#value' => isset($node->privacy['vid']) ? $node->privacy['vid'] : 0);
      $form['privacy']['eid'] = array('#type' => 'value', '#value' => isset($node->privacy['eid']) ? $node->privacy['eid'] : 0);
      if ($nid && !isset($_SESSION['photos_access_' . $node->id()])) {
        $_SESSION['photos_access_' . $node->id()] = isset($node->privacy) ? $node->privacy : '';
      }
      $old = ($nid && isset($_SESSION['photos_access_' . $nid])) ? $_SESSION['photos_access_' . $nid] : array();
      $default_viewid = isset($node->privacy['viewid']) ? $node->privacy['viewid'] : 0;
      $form['privacy']['viewid'] = array(
        '#type' => 'radios',
        '#title' => t('Privacy'),
        '#default_value' => $default_viewid,
        '#options' => array(t('Open'), t('Locked'), t('Designated users'), t('Password required')),
        '#prefix' => '<div id="photos_access_privacy">',
        '#suffix' => '</div>',
        '#ajax' => array(
          'callback' => 'photos_access_privacy_form_ajax',
          'event' => 'change',
          'progress' => array(
            'type' => 'throbber',
            'message' => NULL
          )
        )
      );
      // Prep password field.
      $display_password = ' class="photos_access-hidden-field"';
      if ($default_viewid == 3) {
        $display_password = '';
      }
      $form['privacy']['pass'] = array(
        '#type' => 'password',
        '#title' => t('Password'),
        '#default_value' => isset($node->privacy['pass']) ? $node->privacy['pass'] : '',
        '#prefix' => '<div id="photos_access_password"' . $display_password . '>',
        '#suffix' => '</div>',
      );
      // Prep designated users field.
      $display_user = ' class="photos_access-hidden-field"';
      if ($default_viewid == 2) {
        $display_user = '';
      }
      $userhelp = t('Separated by commas. eg: username1,username2,username3.');
      $form['privacy']['viewuser'] = array(
        '#type' => 'entity_autocomplete',
        '#title' => t('Designated users'),
        '#description' => t('Add people who will have access to view this node.') . ' ' . (isset($old['viewuser']) ? t('@help The following users have access:', array('@help' => $userhelp)) . ' ' : $userhelp),
        '#target_type' => 'user',
        '#tags' => TRUE,
        '#default_value' => (isset($node->privacy['viewuser']) && !is_array($node->privacy['viewuser'])) ? $node->privacy['viewuser'] : NULL,
        '#process_default_value' => FALSE,
        '#prefix' => '<div id="photos_access_viewuser"' . $display_user. '>',
        '#suffix' => '</div>',
      );
      if (!empty($old['viewuser'])) {
        foreach ($old['viewuser'] as $u) {
          $form['privacy']['viewremove'][$u->uid] = array(
            '#type' => 'checkbox',
            '#default_value' => isset($node->viewremove[$u->uid]) ? $node->viewremove[$u->uid] : '',
            '#title' => t('Delete: @name', array('@name' => $u->name)),
            '#prefix' => '<div class="photos_access_remove">',
            '#suffix' => '</div>',
          );
        }
      }
      $form['privacy']['updateuser'] = array(
        '#type' => 'entity_autocomplete',
        '#title' => t('Add collaborators'),
        '#target_type' => 'user',
        '#tags' => TRUE,
        '#default_value' => (isset($node->privacy['updateuser']) && !is_array($node->privacy['updateuser'])) ? $node->privacy['updateuser'] : NULL,
        '#description' => t('Add people who will have the authority to edit this node.') . ' ' . (isset($old['updateuser']) ? t('@help collaboration users list:', array('@help' => $userhelp)) . ' ' : $userhelp),
      );
      if (!empty($old['updateuser'])) {
        foreach ($old['updateuser'] as $u) {
          $form['privacy']['updateremove'][$u->uid] = array(
            '#type' => 'checkbox',
            '#default_value' => isset($node->updateremove[$u->uid]) ? $node->updateremove[$u->uid] : '',
            '#title' => t('Delete: @name', array('@name' => $u->name)),
            '#prefix' => '<div class="photos_access_updateremove">',
            '#suffix' => '</div>',
          );
        }
      }
      $form['#attached']['library'][] = 'photos_access/photos_access.node.form';
      // Make sure $node->privacy is available in node_insert and node_update.
      $form['#entity_builders'][] = 'photos_access_node_builder';
      // @todo form validation via field API.
    }
    if ($node_type == 'photos') {
      // Move files if needed.
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          $form['actions'][$action]['#submit'][] = 'photos_access_move_files_form_submit';
        }
      }
    }
  }
}

/**
 * Update privacy form when radio selection changes.
 */
function photos_access_privacy_form_ajax(&$form, FormStateInterface $form_state) {
  $privacy = $form_state->getValue('privacy');
  $response = new AjaxResponse();
  $response->addCommand(new CssCommand('#photos_access_viewuser', array('display' => 'none')));
  $response->addCommand(new CssCommand('#photos_access_password', array('display' => 'none')));
  if ($privacy['viewid'] == 2) {
    // Users.
    $response->addCommand(new CssCommand('#photos_access_viewuser', array('display' => 'block')));
  }
  elseif ($privacy['viewid'] == 3) {
    // Password.
    $response->addCommand(new CssCommand('#photos_access_password', array('display' => 'block')));
  }
  return $response;
}

/**
 * Form submission handler for private file management.
 *
 * @see photos_access_form_node_form_alter()
 */
function photos_access_move_files_form_submit(&$form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  // Check privacy settings.
  $privacy = $form_state->getValue('privacy');
  $public = FALSE;
  if (isset($privacy['viewid']) && $privacy['viewid'] == 0) {
    // Gallery is open, move files to public.
    $public = TRUE;
  }

  // Check for private file path.
  if (PrivateStream::basePath()) {
    // Move files if needed.
    // @todo Batch API.
    photos_access_move_files($node, $public);
  }
  else {
    if (!$public) {
      // Set warning message.
      drupal_set_message(t('Warning: image files can still be accessed by visiting the direct URL.
        For better security, ask your website admin to setup a private file path.'), 'warning');
    }
  }
}

/**
 * Move files from public to private and private to public as needed.
 */
function photos_access_move_files($node, $public = TRUE) {
  $nid = $node->id();
  // Get user account.
  $album_uid = db_query("SELECT uid FROM {node_field_data} WHERE nid = :nid", array(':nid' => $nid))->fetchField();
  $account = \Drupal::entityManager()->getStorage('user')->load($album_uid);
  // Query all files in album.
  $results = db_query("SELECT fid FROM {photos_image} WHERE pid = :nid", array(':nid' => $nid));
  // Check file wrapper.
  $default_sheme = file_default_scheme();
  $private_scheme = 'private';
  $file_wrapper = $private_scheme . '://';
  $old_file_wrapper = $default_sheme . '://';
  $new_scheme = $private_scheme;
  if ($public) {
    // Move files to default filesystem.
    $file_wrapper = $default_sheme . '://';
    $old_file_wrapper = $private_scheme . '://';
    $new_scheme = $default_sheme;
  }
  $cache_tags = array();
  foreach ($results as $result) {
    $fid = $result->fid;
    $file = File::load($fid);
    $uri = $file->GetFileUri();
    if (strstr($uri, $file_wrapper)) {
      // File is already in correct place.
      // @note continue (check all) or break (assume the rest are also the same)?
      // - mixed private and public files could be in the same album if private
      // - file path is setup after uploading some images.
      continue;
    }

    // Prepare file directory.
    photos_check_path($new_scheme, $file, $account);
    // Move file.
    $new_uri = str_replace($old_file_wrapper, $file_wrapper, $uri);
    file_move($file, $new_uri);
    // Clear image page cache.
    $cache_tags[] = 'photos:image:' . $fid;
  }
  // Clear album page cache.
  $cache_tags[] = 'photos:album:' . $nid;
  // Invalidate image page and album page cache as needed.
  Cache::invalidateTags($cache_tags);
}

/**
 * Entity form builder to add the book information to the node.
 *
 * @todo: Remove this in favor of an entity field.
 */
function photos_access_node_builder($entity_type, NodeInterface $entity, &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if (!$form_state->isValueEmpty('privacy')) {
    $entity->privacy = $form_state->getValue('privacy');
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function photos_access_node_update(NodeInterface $node) {
  if (\Drupal::config('photos.settings')->get('photos_access_' . $node->getType())) {
    photos_access_update_access($node, $node->privacy);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function photos_access_node_insert(NodeInterface $node) {
  if (\Drupal::config('photos.settings')->get('photos_access_' . $node->getType())) {
    photos_access_update_access($node, $node->privacy);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function photos_access_node_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  if (\Drupal::config('photos.settings')->get('photos_access_' . $entity->getType())) {
    // Check if album password is required.
    photos_access_request_album_password();
  }

  // No opinion.
  return AccessResult::neutral();
}

/**
 * Album password check.
 */
function photos_access_request_album_password() {
  $args = \Drupal::moduleHandler()->invokeAll('photos_access');
  if (is_array($args)) {
    $current_path = \Drupal::service('path.current')->getPath();
    $path_args = explode('/', $current_path);
    foreach ($args as $arg) {
      if ($arg && isset($path_args[2])) {
        if ($path_args[2]) {
          if ($path_args[2] == 'album') {
            $t = _photos_access_pass_type($path_args[3]);
          }
          else {
            $t = _photos_access_pass_type($path_args[2]);
          }
        }
        if (isset($t['view'])) {
          if ($t['view']->viewid == 3) {
            // $t['view']->pass <> $_SESSION[$t['view']->nid . '_' . session_id()]
            photos_access_pass_validate($t);
          }
        }
      }
    }
  }
}

/**
 * (D7) Implements hook_node_validate().
 *
 * @todo: Remove this in favor of entity field API.
 */
function photos_access_node_validate(NodeInterface $node, $form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  // @todo handle all of this on submit.
  // Check if users can be added to list.
  $old = isset($_SESSION['photos_access_' . $node->id()]) ? $_SESSION['photos_access_' . $node->id()] : array();
  if (isset($node->privacy['updateuser']) && !empty($node->privacy['updateuser'])) {
    $old_check = isset($old['updateuser']) ? $old['updateuser'] : array();
    if ($userdate = _photos_access_user_validate($node->privacy['updateuser'], $old_check)) {
      $form_state->setErrorByName('privacy][updateuser', $userdate);
    }
  }
  if (isset($node->privacy['viewid']) && $node->privacy['viewid'] == 2) {
    if (isset($node->privacy['viewuser']) && !empty($node->privacy['viewuser'])) {
      $old_check = isset($old['viewuser']) ? $old['viewuser'] : array();
      if ($userdate = _photos_access_user_validate($node->privacy['viewuser'], $old_check)) {
        $form_state->setErrorByName('privacy][viewuser', $userdate);
      }
    }
  }

  // Check if password is empty.
  // @todo workaround: access denied if no password.
  if (isset($node->privacy['viewid']) && $node->privacy['viewid'] == 3) {
    if (isset($node->privacy['pass']) && empty($node->privacy['pass'])) {
      $form_state->setErrorByName('privacy][pass', t('Password required.'));
    }
  }
}

/**
 * Validate user access to node.
 */
function _photos_access_user_validate($privacy, $oldprivacy) {
  $user = \Drupal::currentUser();
  $t = preg_split('/,|，/', $privacy);
  $name = array();
  if (is_array($oldprivacy)) {
    foreach ($oldprivacy as $list) {
      $name[] = $list->name;
    }
  }
  // @todo handle all this on submit.
  $output = '';
  foreach ($t as $a) {
    $a = trim($a);
    if ($a <> $user->name) {
      if (in_array($a, $name)) {
        $output = t('User is already on the list: @name.', array('@name' => $a));
      }
      elseif (!$u = _photos_access_user(array('name' => $a))) {
        $output = t('The user account does not exist: @name.', array('@name' => $a));
      }
    }
    else {
       $output = t("You do not need to add your self to this list.");
    }
  }

  return $output;
}

/**
 * Update access to album.
 */
function photos_access_update_access(NodeInterface $node, $privacy_settings) {
  if (\Drupal::config('photos.settings')->get('photos_access_' . $node->getType())) {
    if (!$privacy_settings['eid']) {
      if ($privacy_settings['updateuser']) {
        // Check if row already exists for this node.
        $acc['updateid'] = db_query("SELECT id FROM {photos_access_album} WHERE nid = :nid", array(':nid' => $node->id()))->fetchField();
        if ($acc['updateid']) {
          // Update existing record.
          db_update('photos_access_album')
            ->fields(array(
              'viewid' => $privacy_settings['viewid'],
              'updateid' => 1
            ))
            ->condition('id', $acc['updateid'])
            ->execute();
        }
        else {
          // Enter new record.
          $acc['updateid'] = db_insert('photos_access_album')
            ->fields(array(
              'nid' => $node->id(),
              'viewid' => $privacy_settings['viewid'],
              'updateid' => 1
            ))
            ->execute();
        }
        _photos_access_usersave($privacy_settings['updateuser'], $acc['updateid']);
      }
    }
    else {
      $remove = FALSE;
      if (isset($privacy_settings['updateremove']) && !empty($privacy_settings['updateremove'])) {
        $remove = _photos_access_usersdel($privacy_settings['updateremove'], $privacy_settings['eid']);
      }
      if (isset($privacy_settings['updateuser']) && !empty($privacy_settings['updateuser'])) {
        _photos_access_usersave($privacy_settings['updateuser'], $privacy_settings['eid']);
        db_query('UPDATE {photos_access_album} SET pass = 1 WHERE id = :id', array(':id' => $privacy_settings['eid']));
      }
      elseif ($remove) {
        db_query('UPDATE {photos_access_album} SET pass = 0 WHERE id = :id', array(':id' => $privacy_settings['eid']));
      }
      $acc['updateid'] = $privacy_settings['eid'];
    }

    if (!$privacy_settings['vid']) {
      $acc['viewid'] = db_insert('photos_access_album')
        ->fields(array(
          'nid' => $node->id(),
          'viewid' => isset($privacy_settings['viewid']) ? $privacy_settings['viewid'] : 0,
          'pass' => isset($privacy_settings['pass']) ? md5($privacy_settings['pass']) : 0
        ))
        ->execute();
      if ($privacy_settings['viewid'] && $privacy_settings['viewuser']) {
        _photos_access_usersave($privacy_settings['viewuser'], $acc['viewid']);
      }
    }
    else {
      switch ($privacy_settings['viewid']) {
        case 0:
        case 1:
          db_query('UPDATE {photos_access_album} SET viewid = :viewid WHERE id = :id',
            array(
              ':viewid' => $privacy_settings['viewid'],
              ':id' => $privacy_settings['vid']
            )
          );
          _photos_access_usersdel(0, $privacy_settings['vid'], 1);
      break;
      case 2:
        db_query('UPDATE {photos_access_album} SET viewid = :viewid WHERE id = :id',
          array(
            ':viewid' => $privacy_settings['viewid'],
            ':id' => $privacy_settings['vid']
          )
        );
        if ($privacy_settings['viewuser']) {
          _photos_access_usersave($privacy_settings['viewuser'], $privacy_settings['vid']);
        }
        if (isset($privacy_settings['viewremove'])) {
          _photos_access_usersdel($privacy_settings['viewremove'], $privacy_settings['vid']);
        }
      break;
      case 3:
        // @todo add option to integrate aes module and encrypt passwords with that.
        $old = isset($_SESSION['photos_access_' . $node->id()]) ? $_SESSION['photos_access_' . $node->id()] : array();
        $old_pass = isset($old['pass']) ? $old['pass'] : '';
        $pass = isset($privacy_settings['pass']) ? md5($privacy_settings['pass']) : $old_pass;
        db_query("UPDATE {photos_access_album} SET viewid = :viewid, pass = :pass WHERE id = :id",
          array(
            ':viewid' => $privacy_settings['viewid'],
            ':pass' => $pass,
            ':id' => $privacy_settings['vid']
          )
        );
        _photos_access_usersdel(0, $privacy_settings['vid'], 1);
      }
      $acc['viewid'] = $privacy_settings['viewid'];
      $acc['vid'] = $privacy_settings['vid'];
    }
    $_SESSION['photos_access_ac_' . $node->id()] = $acc;
    unset($_SESSION['photos_access_' . $node->id()]);
  }
}

/**
 * Implements hook_node_load().
 */
function photos_access_node_load($nodes) {
  foreach ($nodes as $nid => $node) {
    $result = db_query('SELECT * FROM {photos_access_album} WHERE nid = :nid', array(':nid' => $nid));
    $info = array();
    foreach ($result as $a) {
      if ($a->updateid) {
        // Unique ID
        $info['privacy']['eid'] = $a->id;
        $info['privacy']['updateid'] = 1;
        $info['privacy']['viewid'] = $a->viewid;
        $info['privacy']['updateuser'] = _photos_access_userlist($a->id);
      }
      else {
        $info['privacy']['vid'] = $a->id;
        $info['privacy']['viewid'] = $a->viewid;
        if ($a->viewid == 3) {
          $info['privacy']['pass'] = $a->pass;
        }
        $info['privacy']['viewuser'] = _photos_access_userlist($a->id);
      }
    }
    if (isset($info['privacy'])) {
      $nodes[$nid]->privacy = $info['privacy'];
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function photos_access_node_delete(NodeInterface $node) {
  db_query('DELETE FROM {photos_access_album} WHERE nid = :nid', array(':nid' => $node->id()));
  if (isset($node->privacy['vid'])) {
    db_query('DELETE FROM {photos_access_user} WHERE id = :id', array(':id' => $node->privacy['vid']));
  }
  if (isset($node->privacy['eid'])) {
    db_query('DELETE FROM {photos_access_user} WHERE id = :id', array(':id' => $node->privacy['eid']));
  }
}

/**
 * Delete user from album access list.
 */
function _photos_access_usersdel($value, $id, $type = 0) {
  if ($type) {
    db_query('DELETE FROM {photos_access_user} WHERE id = :id', array(':id' => $id));
  }
  elseif (is_array($value)) {
    $count = count($value);
    $i = 0;
    foreach ($value as $key => $remove) {
      if ($remove) {
        ++$i;
        db_query('DELETE FROM {photos_access_user} WHERE id = :id AND uid = :uid', array(':id' => $id, ':uid' => $key));
      }
    }
    if ($count == $i) return TRUE;
  }
}

/**
 * List of users who have access to album.
 */
function _photos_access_userlist($id) {
  $result = db_query('SELECT u.uid, u.name FROM {users_field_data} u INNER JOIN {photos_access_user} a ON u.uid = a.uid WHERE a.id = :id',
    array(
      ':id' => $id
    )
  );
  $users = array();
  foreach ($result as $a) {
    $u = new stdClass();
    $u = $a;
    $u->username = array(
      '#theme' => 'username',
      '#account' => $a
    );
    $users[] = $u;
  }
  return $users;
}

/**
 * Save users to access album list.
 */
function _photos_access_usersave($value, $id) {
  $values = array();
  foreach ($value as $target) {
    $values[] = array(
      'id' => $id,
      'uid' => $target['target_id']
    );
  }
  if (isset($values[0])) {
    // Insert users into photos access table.
    $query = db_insert('photos_access_user')->fields(array('id', 'uid'));
    foreach ($values as $record) {
      $query->values($record);
    }
    $query->execute();
  }
}

/**
 * Implements hook_node_access_records().
 */
function photos_access_node_access_records(NodeInterface $node) {
  $user = \Drupal::currentUser();
  if (\Drupal::config('photos.settings')->get('photos_access_' . $node->getType())) {
    if (isset($node->privacy['vid'])) {
      // @todo cleanup?
      $acc['updateid'] = isset($node->privacy['eid']) ? $node->privacy['eid'] : 0;
      $acc['viewid'] = isset($node->privacy['viewid']) ? $node->privacy['viewid'] : '';
      $acc['vid'] = $node->privacy['vid'];
    }
    else {
      $acc = isset($_SESSION['photos_access_ac_' . $node->id()]) ? $_SESSION['photos_access_ac_' . $node->id()] : '';
    }
    // @todo test switching from locked to password.
    if (isset($acc['vid']) || isset($acc['updateid'])) {
      // Author has full access to all albums they create.
      $grants[] = array(
        'realm' => 'photos_access_author',
        'gid' => $node->getOwnerId(),
        'grant_view' => 1,
        'grant_update' => 1,
        'grant_delete' => 1,
        'priority' => 0,
      );
      // If viewid is 1:locked, only author can view it.
      if ($acc['viewid'] <> 1) {
        // Open is 0.
        $photos_access_gid = 0;
        if ($acc['viewid'] <> 0) {
          // If not open use {node}.nid.
          $photos_access_gid = $node->id();
        }
        $grants[] = array(
          'realm' => 'photos_access',
          'gid' => $photos_access_gid,
          'grant_view' => 1,
          'grant_update' => 0,
          'grant_delete' => 0,
          'priority' => 0,
        );
      }
      // Access for collaborators.
      if (isset($acc['updateid']) && !empty($acc['updateid'])) {
        $grants[] = array(
          'realm' => 'photos_access_update',
          'gid' => $node->id(),
          'grant_view' => 1,
          'grant_update' => 1,
          'grant_delete' => 0,
          'priority' => 0,
        );
      }
      return $grants;
    }
    if (isset($_SESSION['photos_access_ac_' . $node->id()])) {
      unset($_SESSION['photos_access_ac_' . $node->id()]);
    }
  }
}

/**
 * Implements hook_photos_access().
 */
function photos_access_photos_access() {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);
  $args = array();
  if (isset($path_args[2]) && $path_args[1] == 'node' && is_numeric($path_args[2])) {
    return array($path_args[2]);
  }
}

/**
 * Implements hook_node_grants().
 */
function photos_access_node_grants(\Drupal\Core\Session\AccountInterface $account, $op) {
  // Always grant access to view open albums.
  $viewid = array(0);

  // Set uid for author realm to access own albums.
  $grants['photos_access_author'] = array($account->id());

  // Check for private albums that user has access to.
  $result = db_query('SELECT a.* FROM {photos_access_album} a INNER JOIN {photos_access_user} b ON a.id = b.id WHERE b.uid = :uid',
    array(
      ':uid' => $account->id()
    )
  );
  foreach ($result as $a) {
    if ($a->updateid) {
      $updateid[] = $a->nid;
    }
    elseif ($a->viewid) {
      $viewid[] = $a->nid;
    }
  }

  // hook_photos_access()
  // - Return array of nids to check for user access.
  // - Only album nids that require password.
  $args = \Drupal::moduleHandler()->invokeAll('photos_access');

  if (is_array($args)) {
    foreach ($args as $arg) {
      $result = db_query('SELECT id, nid, viewid, pass FROM {photos_access_album} WHERE nid = :nid', array(':nid' => $arg));
      foreach ($result as $a) {
        // Password is required, check if password is set.
        if ($a->viewid == 3 && isset($_SESSION[$a->nid . '_' . session_id()]) && $_SESSION[$a->nid . '_' . session_id()] == $a->pass) {
          $viewid[] = $a->nid;
        }
      }
    }
  }

  switch ($op) {
    case 'view':
      // Array of gid's for realm.
      $grants['photos_access'] = $viewid;
      if (isset($updateid[0])) {
        $grants['photos_access_update'] = $updateid;
      }
    break;
    case 'update':
      if (isset($updateid[0])) {
        $grants['photos_access_update'] = $updateid;
      }
    break;
  }
  return $grants;
}

/**
 * Password entry page.
 */
function photos_access_page($node) {
  if ($node) {
    $output = \Drupal::formBuilder()->getForm('photos_access_pass_form', $node);
    return $output;
  }
  else {
    throw new NotFoundHttpException();
  }
}

/**
 * Check validation type.
 */
function _photos_access_pass_type($id, $op = 0) {
  if ($op) {
    //photos.module
    $result = db_query('SELECT a.*, n.uid, n.type, n.status FROM {photos_access_album} a
      INNER JOIN {node_field_data} n ON a.nid = n.nid INNER JOIN {photos_image} p ON a.nid = p.pid WHERE p.fid = :id',
      array(
        ':id' => $id
      )
    );
  }
  else {
    $result = db_query('SELECT a.*, n.uid, n.type, n.status FROM {photos_access_album} a
      INNER JOIN {node_field_data} n ON a.nid = n.nid WHERE a.nid = :id',
      array(
        ':id' => $id
      )
    );
  }
  $t = array();
  foreach ($result as $ac) {
    if ($ac->viewid == 3) {
      // Password authentication.
      $t['view'] = $ac;
    }
    elseif ($ac->updateid && $ac->pass) {
      // Update privileges.
      $t['update'] = $ac;
    }
    else {
      // Pass to node_access verification.
      $t['node'] = $ac;
    }
  }
  return $t;
}

/**
 * Check password on node page.
 */
function photos_access_pass_validate($t) {
  $user = \Drupal::currentUser();
  // Check if admin or author.
  if ($user->id() == 1 || isset($t['view']->uid) && $t['view']->uid == $user->id()) return TRUE;
  if (isset($t['update']->pass)) {
    // Check if collaborator.
    $result = db_query('SELECT uid FROM {photos_access_user} WHERE id = :id', array(':id' => $t['update']->id));
    foreach ($result as $a) {
      if ($a->uid == $user->id()) return TRUE;
    }
  }
  if ($t['view']->nid) {
    if (isset($_SESSION[$t['view']->nid . '_' . session_id()])) {
      // Check if password matches node password.
      if ($_SESSION[$t['view']->nid . '_' . session_id()] == $t['view']->pass) {
        return TRUE;
      }
      // If password is set, but does not match re enter password.
      drupal_set_message(t('Password has expired.'));

      // Redirect.
      $current_path = \Drupal::service('path.current')->getPath();
      $redirect_url = Url::fromUri('base:privacy/pass/' . $t['view']->nid, array(
        'query' => array(
          'destination' => $current_path
        )
      ))->toString();
      $response = new RedirectResponse($redirect_url);
      $response->send();
      exit();
    }
    else {
      // If password is not set, password is required.
      drupal_set_message(t('Password required.'));

      // Redirect.
      $current_path = \Drupal::service('path.current')->getPath();
      $redirect_url = Url::fromUri('base:privacy/pass/' . $t['view']->nid, array(
        'query' => array(
          'destination' => $current_path
        )
      ))->toString();
      $response = new RedirectResponse($redirect_url);
      $response->send();
      exit();
    }
  }
}

/**
 * Check if user account exists.
 */
function _photos_access_user($u) {
  if (isset($u['name'])) {
    $ac = db_query("SELECT uid, name FROM {users_field_data} WHERE name = :name", array(':name' => $u['name']))->fetchObject();
  }
  elseif (isset($u['uid'])) {
    $ac = db_query('SELECT uid, name FROM {users_field_data} WHERE uid = :uid', array(':uid' => $u['uid']))->fetchObject();
  }
  if (isset($ac->uid)) return $ac;
}

/**
 * Helper function to return options for views album privacy filter.
 */
function _photos_access_album_views_options() {
  return array(
    0 => t('Open'),
    1 => t('Locked'),
    2 => t('Designated users'),
    3 => t('Password required')
  );
}

/**
 * Implements hook_views_data().
 */
function photos_access_views_data() {
  $data = array();
  $data['photos_access_album'] = array();
  $data['photos_access_album']['table'] = array();
  $data['photos_access_album']['table']['group'] = t('Photos');
  $data['photos_access_album']['table']['provider'] = 'photos_access';

  // Join node_field_data.
  $data['photos_access_album']['table']['join'] = array(
    'node_field_data' => array(
      'left_field' => 'nid',
      'field' => 'nid',
    ),
  );

  // Numeric field, exposed as a field, sort, filter, and argument.
  $data['photos_access_album']['viewid'] = array(
    'title' => t('Privacy'),
    'help' => t('Album privacy setting.'),
    'field' => array(
      'id' => 'numeric',
    ),
    'sort' => array(
      'id' => 'standard',
    ),
    'filter' => array(
      'id' => 'in_operator',
      'options callback' => '_photos_access_album_views_options'
    ),
    'argument' => array(
      'id' => 'numeric',
    ),
  );

  return $data;
}
