<?php

/**
 * @file
 * Allows mappings of PDFs to site content.
 */

/**
 * Implements hook_help().
 */
function fillpdf_help($path, $arg) {
  switch ($path) {
    case 'admin/help#fillpdf':
      $content = t('See the <a href="!documentation">documentation on drupal.org</a> for a full description of and guide to this module.', ['!documentation' => \Drupal\Core\Url::fromUri('http://drupal.org/documentation/modules/fillpdf')]);
      return $content;
    case 'admin/structure/fillpdf':
      if (\Drupal::moduleHandler()->moduleExists('help')) {
        return t('See the !link for an explanation on dowloading these forms to PDF',
          ['!link' => \Drupal::l(t('documentation'), \Drupal\Core\Url::fromUri('http://drupal.org/documentation/modules/fillpdf'))]);
      }
      else {
        return t('Activate the help module if you need an explanation on downloading these forms to PDF.');
      }
      break;
  }

  return '';
}
